export const SET_MOVIES = 'SET_MOVIES';
export const SET_MOVIE = 'SET_MOVIE';
export const FETCH_MOVIES_FAIL = 'FETCH_MOVIES_FAIL';
export const FETCH_MOVIE_FAIL = 'FETCH_MOVIES_FAIL';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const DELETE_QUOTE = 'DELETE_QUOTE';
